### ISSUE TITLE
Detach this fork and purge the original

### ISSUE THREAD

**Issue by alexander-nitsche** [FriendsOfTYPO3/sys_action#5]
This repository is a fork of `https://github.com/TYPO3-CMS/sys_action` but has become the original in meantime. Detach it and purge the `TYPO3-CMS/sys_action` repository to streamline things.

To detach a GitHub fork and transform into own repository do

> if you visit support.github.com/contact?tags=rr-forksm and type as subject "detach fork from parent repo", the option is given of getting help from GitHub's Virtual Assistant via web-based chat. It asks for the repo URL, you give it, and voila! It's done. –
    phlummox, Jan 25 at 15:25

following https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting.

**Comment by ohader** [comment]
Initiated detaching process

**Comment by ohader** [comment]
Detached ✅
